codecov:
  require_ci_to_pass: yes
  strict_yaml_branch: main
  max_report_age: off

coverage:
  precision: 2
  round: down
  range: "0...100"

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: no