name: Codecov Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Run codecov action
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Codecov
        # You may pin to the exact commit or the version.
        # uses: codecov/codecov-action@5a8bb4701eca7ba3673f21664b887f652c58d0a3
        uses: codecov/codecov-action@v2.0.3
        with:
          # Repository upload token - get it from codecov.io. Required only for private repositories
          token: d4b2d1fb-2859-432a-bd35-49d214d4f8db
          
          
